//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLab_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Members = new HashSet<Member>();
        }
    
        public string MaCV { get; set; }
        public string TenCV { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public Nullable<bool> HoanThanh { get; set; }
        [System.ComponentModel.Browsable(false)]
        public string MaNQL { get; set; }
        [System.ComponentModel.Browsable(false)]
        public string MaDA { get; set; }
        public string NoiDung { get; set; }

        [System.ComponentModel.Browsable(false)]
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.ComponentModel.Browsable(false)]
        public virtual ICollection<Member> Members { get; set; }
    }
}
