//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLab_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Jobs = new HashSet<Job>();
            this.Members = new HashSet<Member>();
        }
    
        public string MaDA { get; set; }
        public string TenDA { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public Nullable<double> TienDo { get; set; }
        [System.ComponentModel.Browsable(false)]
        public string MaNQL { get; set; }
        public string NoiDung { get; set; }
        [System.ComponentModel.Browsable(false)]
        public Nullable<bool> HoanThanh { get; set; }
        [System.ComponentModel.Browsable(false)]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.ComponentModel.Browsable(false)]
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.ComponentModel.Browsable(false)]
        public virtual ICollection<Member> Members { get; set; }
    }
}
